config/routes.rb
Rails.application.routes.draw do
  resources :pins

  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy]
	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def new
		@pin = Pin.new
	end

	def show
	end

	def create
		@pin = Pin.new(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Successfully created new Pin."
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was updated."
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end
	private
	
	def pin_params
		params.require(:pin).permit(:title, :description)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Pin Board
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	- flash.each do |name,msg|
		= content_tag :div, msg, class: "alert alert-info"
		
	= yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h2
			= pluralize(@pin.errors.count, "error")
			prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.input :title, input_html: {class: 'form-control'}
		
	.form-group
		= f.input :description, input_html: {class: 'form-control'}

	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
%h1 Edit Pin
= render 'form'

=link_to "Cancel", pin_path 

app/views/pins/index.html.haml
= link_to "New Pin", new_pin_path
- @pins.each do |pin|
	%h2= link_to pin.title, pin

app/views/pins/new.html.haml
%h1 New form

= render 'form'

= link_to "Back", root_path

app/views/pins/show.html.haml
%h1= @pin.title
%p= @pin.description

= link_to "Back", root_path
= link_to "Edit", edit_pin_path
= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }